import remarkGfm from "remark-gfm";
import nextra from "nextra";
import NextBundleAnalyzer from "@next/bundle-analyzer";
const withBundleAnalyzer = NextBundleAnalyzer({
  enabled: process.env.ANALYZE === "true",
});
/**
 * CSP headers
 * img-src https to allow loading images from SSO providers
 */
const cspHeader = `
  default-src 'self' https: wss:;
  script-src 'self' 'unsafe-eval' 'unsafe-inline' https:;
  style-src 'self' 'unsafe-inline' https:;
  img-src 'self' https: blob: data:;
  media-src 'self' https: blob: data:;
  font-src 'self' https:;
  frame-src 'self' https:;
  worker-src 'self' blob:;
  object-src 'none';
  base-uri 'self';
  form-action 'self';
  frame-ancestors 'self' https://studio.lamatic.ai;
  upgrade-insecure-requests;
  block-all-mixed-content;
`;
// nextra config
const withNextra = nextra({
  theme: "nextra-theme-docs",
  themeConfig: "./theme.config.tsx",
  mdxOptions: {
    remarkPlugins: [remarkGfm],
  },
  defaultShowCopyCode: true,
});
// next config
const nextraConfig = withNextra({
  // assetPrefix:'/docs/',
  experimental: {
    scrollRestoration: true,
  },
  typescript: {
    ignoreBuildErrors: true,
  },
  eslint: {
    // ESLint behaves weirdly in this monorepo.
    ignoreDuringBuilds: true,
  },
  transpilePackages: ["react-tweet", "react-syntax-highlighter", "geist"],
  images: {
    remotePatterns: [
      {
        protocol: "https",
        hostname: "lamatic.ai",
        port: "",
        pathname: "/**",
      },
    ],
  },
  headers() {
    return [
      {
        source: "/:path*",
        headers: [
          {
            key: "x-frame-options",
            value: "SAMEORIGIN",
          },
          {
            key: "X-Content-Type-Options",
            value: "nosniff",
          },
          {
            key: "Referrer-Policy",
            value: "strict-origin-when-cross-origin",
          },
          {
            key: "Permissions-Policy",
            value: "autoplay=*, fullscreen=*, microphone=*",
          },
        ],
      },
      {
        source: "/blog/:path*",
        headers: [
          { key: "x-forwarded-proto", value: "https" },
          { key: "x-forwarded-host", value: "blog.lamatic.ai" },
        ],
      },
      {
        source: "/:path((?!api).*)*",
        headers: [
          {
            key: "Content-Security-Policy",
            value: cspHeader.replace(/\n/g, ""),
          },
        ],
      },
    ];
  },
  redirects: async () => [
    ...nonPermanentRedirects.map(([source, destination]) => ({
      source,
      destination,
      permanent: false,
    })),
    ...permanentRedirects.map(([source, destination]) => ({
      source,
      destination,
      permanent: false,
    })),
  ],
  rewrites: async () => {
    return {
      beforeFiles: rewrites.map(([source, destination]) => ({
        source,
        destination,
      })),
      fallback: [
        // These rewrites are checked after both pages/public files
        // and dynamic routes are checked
      ],
    };
  },
});
const nonPermanentRedirects = [
  ["/get-demo", "/docs/demo"],
  ["/demo", "/docs/demo"],
  ["/video", "/guides/videos/introducing-lamaticai-2.0"],
  ["/docs/video", "/guides/videos/introducing-lamaticai-2.0"],
  ["/roadmap", "/docs/roadmap"],
  ["/ph", "https://www.producthunt.com/posts/lamatic"],
  ["/issue", "https://github.com/Lamatic/docs/issues/new/choose"],
  ["/new-issue", "https://github.com/Lamatic/docs/issues/new/choose"],
  ["/issues", "https://github.com/Lamatic/docs/issues"],
  ["/get-a-demo", "/docs/demo"],
  // ["/security", "/docs/data-security-privacy"],
  ["/idea", "https://github.com/Lamatic/docs/discussions/new?category=ideas"],
  [
    "/new-idea",
    "https://github.com/Lamatic/docs/discussions/new?category=ideas",
  ],
  ["/ideas", "https://github.com/Lamatic/docs/discussions/categories/ideas"],
  [
    "/gh-support",
    "https://github.com/Lamatic/docs/discussions/categories/support",
  ],
  ["/gh-discussions", "https://github.com/Lamatic/docs/discussions"],
  ["/docs/analytics", "/docs/analytics/overview"],
  [
    "/docs/nodes/data-nodes/search-node",
    "https://lamatic.ai/docs/interface/Widgets/search",
  ],
  ["/launch", "https://blog.lamatic.ai/announcements/lamatic-launch-week/"],
  // Redirect to overview pages
  ...[
    // "/docs/integrations",
    // "/docs/scores",
    // "/docs/datasets",
  ].map((path) => [path, path + "/overview"]),
  // Redirects to bridge all kinds of old links to new links
  // Reorder Tracing section
  /* ["/docs/tracing/overview", "/docs/tracing"],
     ["/docs/tracing-features", "/docs/tracing"],
     ...[
       "sessions",
       "users",
       "tags",
       "url",
     ].map((path) => [`/docs/tracing/${path}`, `/docs/tracing-features/${path}`]),*/
  // User-reported broken links
];
const permanentRedirects = [
["/docs/integrations/Apps","/integrations/apps-data-sources"],
["/docs/workflows/nodes/agents/RAG","/docs/flows/nodes"],
["/docs/integrations/credentials","/integrations/adding-integration"],
// ["/docs/IDE/1._Prompt_IDE","/docs/ide/prompt-ide"],
["/docs/integrations/apps/websearch","/docs/integrations/websearch"],
["/docs/flows/Nodes/Flow/workflow","/docs/flows/nodes"],
["/docs/workflows/nodes/flow","/docs/flows/nodes"],
["/docs/workflows/nodes","/docs/flows/nodes"],
["/docs/workflows/nodes/flow/api","/docs/flows/nodes"],
["/docs/models/api-key-guide","/integrations/models"],
["/docs/Trash/graphQL/API_Docs","/docs/interface/graphql"],
["/docs/workflows/nodes/agents/LLM","/docs/flows/nodes"],
["/docs/workflows/nodes/agents/instructor","/docs/flows/nodes"],
["/docs/workflows/nodes/flow/webhook","/docs/interface/webhooks"],
["/docs/flows/low-code_config","/docs/flows/flow-config"],
["/docs/models/Anthropic","/integrations/models/anthropic"],
["/docs/models/Mistral-AI","/docs/models"],
["/docs/models/Voyage-AI","/integrations/models/voyage-ai"],
["/docs/models/Open-AI","/integrations/models/open-ai"],
["/docs/models/Groq","/integrations/models/groq"],
["/docs/models/Gemini","/integrations/models/gemini"],
["/docs/workflows/nodes/agents/quality-check","/docs/flows/nodes"],
["/docs/models/Amazon","/integrations/models/bedrock"],
["/docs/IDE/3._GraphQL_IDE","/docs/ide/graphql_ide"],
["/docs/workflows/Nodes/Data/index-node","/docs/flows/nodes"],
["/docs/workflows/Nodes/Flow/webhook","/docs/interface/webhooks"],
["/docs/studio/role-based-Access","/docs/studio-role-based-access"],
["/docs/workflows/nodes/data-nodes/vectorize","/docs/context/vectordb"],
["/docs/Trash/widgets/search","/docs/interface/widgets/search"],
["/docs/flows/Concepts/prompts","/docs/ide/prompt-ide"],
["/docs/workflows/Nodes/Flow/experiment","/docs/ai-middleware/architecture"],
["/docs/flows/Nodes/AI/summarize","/docs/flows/nodes"],
["/docs/workflows/prompts","/docs/ide/prompt-ide"],
["/docs/flows/Nodes/Flow/experiment","/docs/ai-middleware/architecture"],
["/docs/flows/Nodes/AI/MultiModal","/docs/models"],
["/docs/workflows/nodes/data-nodes/read-file","/docs/flows/nodes"],
["/docs/experiments","/docs/ai-middleware/architecture"],
["/docs/workflows/nodes/flow/followup","/docs/flows/nodes"],
// ["/docs/studio/Workspace","/docs/studio-overview"],
["/docs/workflows/nodes/AI/summarize","/docs/flows/nodes"],
["/docs/Models/api-key-guide","/integrations/models"],
["/docs/jobs/Connections","/docs/jobs"],
["/docs/workflows/nodes/AI/quality-check","/docs/flows/nodes"],
["/docs/integrations/Data/Google_Drive","/docs/integrations/google-drive"],
["/docs/graphQL/Authentication","/docs/interface/graphql"],
["/docs/workflows/nodes/Logic/experiment","/docs/ai-middleware/architecture"],
["/docs/jobs/Sync","/docs/jobs"],
["/docs/workflows/Nodes/Flow/search-web","/docs/integrations/websearch"],
["/docs/studio/Workspace/Settings","/docs/studio-overview"],
["/docs/deployments/versions","/docs/deployments"],
["/docs/Trash/jobs/history","/docs/jobs"],
["/docs/flows/Nodes/Flow/search-web","/docs/integrations/websearch"],
["/docs/Trash/logs/Query","/docs/logs"],
["/docs/workflows/nodes/AI/RAG","/docs/flows/nodes"],
["/docs/workflows/Nodes/Flow","/docs/flows/nodes"],
["/docs/logs/Retry","/docs/logs"],
["/docs/studio/Project/Settings/Jobs","/docs/jobs"],
["/docs/workflows/Nodes/Flow/condition","/docs/flows/nodes"],
["/docs/flows/Nodes/Flow/followup","/docs/flows/nodes"],
["/docs/studio/Account","/docs/studio-overview"],
["/docs/workflows/Nodes/Flow/workflow","/docs/flows"],
["/docs/integrations/Developer","/docs/flows"],
["/docs/workflows/nodes/Logic/workflow","/docs/flows"],
["/docs/IAM","/docs/ai-middleware/architecture"],
["/docs/workflows/nodes/response","/docs/flows/flow-config"],
["/docs/jobs/history","/docs/jobs"],
["/docs/logs/Traces","/docs/logs"],
["/docs/workflows/Concepts/variable_selector","/docs/flows/variables"],
["/docs/context/Method-1:VectorDB","/docs/context/vectordb"],
["/docs/workflows/nodes/AI/generate-image","/docs/flows/nodes"],
["/docs/widgets/search","/docs/interface/widgets/search"],
["/docs/flows/Nodes/Data/index-node","/docs/nodes/data/vectordb-node"],
["/docs/graphQL/Setup","/docs/interface/graphql"],
["/docs/context/Method-1:VectorDB/adding-data","/docs/context/vectordb/adding-data"],
["/docs/integrations/Apps/Slack","/docs/integrations/slack"],
["/docs/studio/Project/Settings","/docs/studio/project"],
["/docs/workflows/nodes/Widgets","/docs/interface/widgets/chat"],
["/docs/Models/usage-cost","/docs/models/benchmark"],
["/docs/workflows/nodes/flow/experiment","/docs/ai-middleware/architecture"],
["/docs/nodes/data-nodes","/docs/flows/nodes"],
["/docs/experiments/Test Runs","/docs/tests/flow-testing#run-a-full-flow-test-for-end-to-end-execution"],
["/docs/workflows/Low Code Builder","/docs/flows/editor"],
["/docs/experiments/Deployment Test","/docs/tests/flow-testing#run-a-full-flow-test-for-end-to-end-execution"],
["/docs/workflows/nodes/data-nodes/index-node","/docs/flows/Nodes"],
["/docs/workflows/nodes/Logic/code","/docs/flows/nodes"],
["/docs/graphQL/API_Docs","/docs/interface/graphql"],
["/docs/nodes/flow/search-web","/docs/integrations/websearch"],
["/docs/nodes/flow/condition","/docs/flows/nodes"],
// ["/docs/Models/Defaults","/docs/models#model-defaults"],
["/docs/widgets/Chat","/docs/interface/widgets/chat"],
["/docs/Trash/widgets/Chat","/docs/interface/widgets/chat"],
["/docs/tests/Test-Runs","/docs/tests/flow-testing"],
["/docs/workflows/nodes/AI/decision-branch","/docs/flows/nodes"],
["/docs/nodes/agents/summarize","/docs/flows/nodes"],
["/docs/IDE/2._Code_IDE","/docs/ide/code_ide"],
["/docs/flows/Nodes/Data","/docs/flows/nodes"],
["/docs/graphQL/Query","/docs/interface/graphql"],
["/docs/workflows/Nodes/Data/vectorize","/docs/context/vectordb"],
["/docs/workflows/nodes/AI/LLM","/docs/flows/nodes"],
["/docs/workflows/response","/docs/flows/flow-config"],
["/docs/flows/Nodes/AI","/docs/flows/nodes"],
["/docs/workflows/Nodes/AI/MultiModal","/docs/models"],
["/docs/workflows/nodes/Logic/webhook","/docs/interface/webhooks"],
["/docs/workflows/nodes/flow/search-web","/docs/integrations/websearch"],
["/docs/flows/Nodes/Data/vectorize","/docs/context/vectordb"],
["/docs/context/Vector_Explorer","/docs/context"],
["/docs/Trash/graphQL/Authentication","/docs/interface/graphql"],
["/docs/workflows/Nodes/Flow/read-website","/docs/flows/nodes"],
["/docs/logs/Query","/docs/logs"],
["/docs/integrations/Data","/integrations"],
["/docs/studio/Account/Settings/API","/docs/studio/project"],
["/docs/workflows/execution-logs","/docs/logs"],
["/docs/studio/Project/Settings/API","/docs/studio/project"],
["/docs/flows/Nodes/Flow/code","/docs/flows/nodes"],
["/docs/Trash/graphQL/Query","/docs/interface/graphql"],
["/docs/Models/model-credentials","/docs/models"],
["/docs/workflows/nodes/flow/workflow","/docs/flows"],
["/docs/playground/Prompt IDE","/docs/ide/prompt-ide"],
["/docs/studio/Account/Settings","/docs/studio-overview"],
["/docs/workflows/Nodes/Flow/followup","/docs/flows/nodes"],
["/docs/playground/Code IDE","/docs/ide/code-ide"],
["/docs/workflows/Nodes/Flow/query-database","/docs/flows/nodes"],
["/docs/workflows/Nodes/Data/read-file","/docs/flows/nodes"],
["/docs/context/vector_stores","/docs/context"],
["/docs/workflows/nodes/Logic","/docs/flows/nodes"],
["/docs/workflows/nodes/flow/read-website","/docs/flows/nodes"],
["/docs/workflows/nodes/agents/summarize","/docs/flows/nodes"],
["/docs/workflows/nodes/data-nodes","/docs/flows/nodes"],
["/docs/flows/Concepts/variable_selector","/docs/flows/variables"],
["/docs/workflows/nodes/Logic/read-website","/docs/flows/nodes"],
["/docs/workflows/nodes/flow/condition","/docs/flows/nodes"],
["/docs/deployments/rollback","/docs/flows/editor"],
["/docs/workflows/workflow_config","/docs/flows/flow-config"],
["/docs/workflows/nodes/flow/code","/docs/flows/nodes"],
["/docs/studio/overview","/docs/studio-overview"],
["/docs/workflows/nodes/Helper/index-node","/docs/nodes/data/vectordb-node"],
["/docs/context/mapping","/docs/context/vectordb/adding-data"],
["/docs/models/model-credentials","/docs/models"],
["/docs/integrations/Developer/posthog","/docs/studio/project"],
["/docs/IDE/Code IDE","/docs/ide/code_ide"],
["/docs/flows/Nodes/Flow/query-database","/docs/flows/nodes"],
["/docs/organization/roles","/docs/studio-overview"],
["/docs/workflows/Nodes/Apps","/docs/flows/nodes"],
["/docs/nodes/flow/followup","/docs/flows/nodes"],
["/docs/experiments/Test Suites","/docs/studio/project"],
["/docs/integrations/Developer/langfuse","/docs/studio/project"],
["/docs/workflows/nodes/AI/instructor","/docs/flows/nodes"],
["/docs/workflows/nodes/AI","/docs/flows/nodes"],
["/docs/workflows/nodes/triggers","/docs/nodes"],
["/docs/workflows/Nodes/Data","/docs/flows/nodes"],
["/docs/studio/Project/Settings/Developer","/docs/studio/project"],
["/docs/flows/Nodes/Data/read-file","/docs/flows/nodes"],
["/docs/workflows/nodes/custom-nodes","/docs/flows/nodes"],
["/docs/vector stores/mapping","/docs/context/vectordb"],
["/docs/vector stores/Vector Stores","/docs/context/vectordb"],
["/docs/workflows/nodes/Logic/api","/docs/flows/nodes"],
["/docs/playground/GraphiQL","/docs/ide/graphql_ide"],
["/docs/workflows/Nodes/Flow/code","/docs/flows/nodes"],
["/docs/workflows/nodes/Logic/search-web","/docs/integrations/websearch"],
["/docs/workflows/Concepts/prompts","/docs/ide/prompt-ide"],
["/docs/workflows/nodes/Logic/followup","/docs/flows/nodes"],
["/docs/workflows/nodes/Helper","/docs/flows/nodes"],
["/docs/workflows/nodes/Helper/vectorize","/docs/context/vectordb"],
["/docs/workflows/Concepts/branching","/docs/flows"],
["/docs/apps/credentials","/docs/flows/nodes"],
["/docs/edge","/docs/deployments"],
["/docs/apps/apps","/docs/flows/nodes"],
["/docs/nodes/agents/RAG","/docs/flows/nodes"],
["/docs/workflows/nodes/Helper/read-file","/docs/flows/nodes"],
["/docs/search-widget","/docs/interface/widgets/search"],
["/docs/nodes/agents/quality-check","/docs/flows/nodes"],
["/docs/workflows/nodes/Logic/query-database","/docs/flows/nodes"],
["/docs/cache","/docs/deployments/cache"],
["/docs/posthog","/docs/studio/project"],
["/docs/workflows/branching","/docs/flows"],
["/docs/workflows/variable_selector","/docs/flows/variables"],
["/docs/nodes/data-nodes/read-file","/docs/flows/nodes"],
["/docs/nodes/data-nodes/vectorize","/docs/flows/nodes"],
["/docs/nodes/flow/webhook","/docs/interface/webhooks"],
["/docs/nodes/data-nodes/index-node","/docs/flows/Nodes"],
["/docs/nodes/flow/read-website","/docs/flows/nodes"],
["/docs/workflows/triggers","/docs/nodes"],
["/docs/nodes/flow/experiment","/docs/ai-middleware/architecture"],
["/docs/nodes/flow/workflow","/docs/flows"],
["/docs/nodes/agents/generate-image","/docs/flows/nodes"],
["/docs/nodes/flow/api","/docs/flows"],
["/docs/nodes/apps","/integrations/apps-data-sources"],
    ["/docs/nodes/apps/airtable-node","/integrations/apps-data-sources/airtable"],
    ["/docs/nodes/apps/crawler-node","/integrations/apps-data-sources/firecrawl"],
    ["/docs/nodes/apps/google-drive-node","/integrations/apps-data-sources/google-drive"],
    ["/docs/nodes/apps/google-sheets-node","/integrations/apps-data-sources/google-sheets"],
    ["/docs/nodes/apps/n8n-node","/integrations/apps-data-sources/n8n"],
    ["/docs/nodes/apps/notion-node","/integrations/apps-data-sources/notion"],
    ["/docs/nodes/apps/onedrive-business-node","/integrations/apps-data-sources/onedrive"],
    ["/docs/nodes/apps/postgres-node","/integrations/apps-data-sources/postgres"],
    ["/docs/nodes/apps/s3-node","/integrations/apps-data-sources/aws-s3"],
    ["/docs/nodes/apps/sharepoint-business-node","/integrations/apps-data-sources/sharepoint"],
    ["/docs/nodes/apps/slack-node","/integrations/apps-data-sources/slack"],
    ["/docs/nodes/apps/smtp-node","/integrations/apps-data-sources"],
    ["/docs/nodes/apps/twilio-node","/integrations/apps-data-sources/twilio"],
    ["/docs/nodes/apps/web-search-node","/integrations/apps-data-sources/websearch"],
    ["/docs/nodes/apps/scraper-node","/integrations/apps-data-sources/firecrawl"],
    ["/docs/nodes/apps/gmail-node","/integrations/apps-data-sources"],
    ["/docs/nodes/apps/cron-node","/integrations/apps-data-sources"],
["/docs/nodes/flow/query-database","/docs/flows/nodes"],
["/docs/vector_stores/vector_stores","/docs/context/vectordb"],
["/docs/vector_stores/mapping","/docs/context/vectordb"],
["/docs/workflows","/docs/flows"],
["/docs/nodes/flow/code","/docs/flows/nodes"],
["/docs/nodes/agents/LLM","/docs/flows/nodes"],
["/docs/home","/docs"],
["/docs/nodes/agents/decision-branch","/docs/flows/nodes"],
["/docs/workflows/Nodes/AI/LLM","/docs/flows/nodes"],
["/docs/workflows/testing","/docs/tests/flow-testing"],
["/docs/workflows/Nodes/AI/RAG","/docs/flows/nodes"],
["/docs/models/usage-cost","/docs/models/benchmark"],
["/docs/apps/marketplace","/docs/integrations"],
["/docs/workflows/nodes/agents","/docs/flows/nodes"],
["/docs/workflows/nodes/agents/decision-branch","/docs/flows/nodes"],
["/docs/workflows/nodes/apps","/docs/flows/nodes"],
["/docs/workflows/nodes/flow/query-database","/docs/flows/nodes"],
["/docs/workflows/nodes/agents/generate-image","/docs/flows/nodes"],
["/docs/models/Azure","/integrations/models/azure-ai-foundry"],
["/docs/integrations/aws-s3","/integrations/apps-data-sources/aws-s3"],
["/docs/integrations/firecrawl","/integrations/apps-data-sources/firecrawl"],
["/docs/integrations/github","/integrations/apps-data-sources/github"],
["/docs/integrations/google-drive","/integrations/apps-data-sources/google-drive"],
["/docs/integrations/google-sheets","/integrations/apps-data-sources/google-sheets"],
["/docs/integrations/teams","/integrations/apps-data-sources/teams"],
["/docs/integrations/n8n","/integrations/apps-data-sources/n8n"],
["/docs/integrations/onedrive","/integrations/apps-data-sources/onedrive"],
["/docs/integrations/postgres","/integrations/apps-data-sources/postgres"],
["/docs/integrations/sharepoint","/integrations/apps-data-sources/sharepoint"],
["/docs/integrations/slack","/integrations/apps-data-sources/slack"],
["/docs/integrations/websearch","/integrations/apps-data-sources/websearch"],
["/docs/models/providers/bedrock","/integrations/models/bedrock"],
["/docs/models/providers/anthropic","/integrations/models/anthropic"],
["/docs/models/providers/azure-ai-foundry","/integrations/models/azure-ai-foundry"],
["/docs/models/providers/azure-openai","/integrations/models/azure-openai"],
["/docs/models/providers/cloudflare","/integrations/models/cloudflare"],
["/docs/models/providers/cohere","/integrations/models/cohere"],
["/docs/models/providers/deepinfra","/integrations/models/deepinfra"],
["/docs/models/providers/deepseek","/integrations/models/deepseek"],
["/docs/models/providers/fireworks-ai","/integrations/models/fireworks-ai"],
["/docs/models/providers/gemini","/integrations/models/gemini"],
["/docs/models/providers/groq","/integrations/models/groq"],
["/docs/models/providers/huggingface","/integrations/models/huggingface"],
["/docs/models/providers/ibm-watsonx-ai","/integrations/models/ibm-watsonx-ai"],
["/docs/models/providers/mistral-ai","/integrations/models/mistral-ai"],
["/docs/models/providers/ollama","/integrations/models/ollama"],
["/docs/models/providers/open-ai","/integrations/models/open-ai"],
["/docs/models/providers/perplexity-ai","/integrations/models/perplexity-ai"],
["/docs/models/providers/together-ai","/integrations/models/together-ai"],
["/docs/models/providers/voyage-ai","/integrations/models/voyage-ai"],
["/docs/models/providers/xai","/integrations/models/xai"],
["/docs/flows/getting-started","/docs/get-started"],
["/docs/nodes/text-llm-node","/docs/nodes/ai/generate-text-node"],
["/docs/integrations/notion","/integrations/apps-data-sources/notion"],
["/docs/integrations","/integrations"],
["/docs/integrations/airtable","/integrations/apps-data-sources/airtable"],
["/docs/nodes/json-generate-node","/docs/nodes/ai/generate-json-node"],
["/docs/nodes/image-gen-node","/docs/nodes/ai/generate-image-node"],
["/docs/nodes/multimodel-node","/docs/nodes/ai/multimodal-node"],
["/docs/nodes/rag-node","/docs/nodes/ai/rag-node"],
["/docs/nodes/supervisor-node","/docs/nodes/ai/supervisor-node"],
["/docs/nodes/agent-classifier-node","/docs/nodes/ai/supervisor-node"],
["/docs/integrations/twilio","/integrations/apps-data-sources/twilio"],
["/docs/integrations/smtp","/integrations/apps-data-sources"],
["/terms","/docs/terms-and-conditions"],
["/privacy","/docs/legal/privacy-policy"],
["/hub/:path*","/:path*"],
["/slack","/docs/slack"],
["/about","/about-us"],
["/docs/Test","/docs/tests"],
["/docs/studio/Project/Settings/keys","/docs/studio/project#api-keys"],
// ["/docs/Logs","https:lamatic.ai/docs/logs"],
// ["/docs/Jobs","https:lamatic.ai/docs/jobs"],
// ["/docs/Integrations","https:lamatic.ai/docs/integrations"],
// ["/docs/Ide","https:lamatic.ai/docs/IDE"],
// ["/docs/Logs","/docs/logs"],
// ["/docs/Jobs","/docs/jobs"],
// ["/docs/Integrations","/docs/integrations"],
// ["/docs/Ide","/docs/IDE"],
["/docs/graphql","/docs/interface/graphql"],
// ["/docs/graphQL","https:lamatic.ai/docs/interface/graphQL"],
["/docs/graphQL","/docs/interface/graphQL"],
["/docs/flows/Low-code","/docs/flows/flow-config"],
// ["/docs/Flows","https:lamatic.ai/docs/flows"],
["/docs/Flows","/docs/flows"],
["/docs/Edge-Deployments","/docs/deployments"],
["/docs/apps/data-sources","/integrations/apps-data-sources"],
["/careers","/docs/career"],
["/marketplace/templates","/templates"],
["/marketplace/apps","/apps"],
["/docs/widgets","/docs/interface/"],
// ["/docs/Reports","https:lamatic.ai/docs/reports"],
["/docs/Reports","/docs/reports"],
["/docs/workflow","/docs/flows"],
["/aboutus","/about-us"],
["/docs/langfuse-integration","/docs/reports/langfuse-integration"],
["/docs/flows/trigger","/docs/flows"],
// ["/labs","https:labs.lamatic.ai"],
["/docs/nodes/extact-from-file-node","/docs/nodes/data/extract-from-file-node"],
["/docs/nodes/chunking-node","/docs/nodes/data/chunking-node"],
["/docs/nodes/vectorize-node","/docs/nodes/data/vectorize-node"],
["/docs/nodes/vector-actions-node","/docs/nodes/data/vector-search-node"],
["/docs/nodes/api-node","/docs/nodes/data/api-node"],
["/docs/nodes/hybrid-search-node","/docs/nodes/data/hybrid-search-node"],
["/docs/nodes/keyword-search-node","/docs/nodes/data/keyword-search-node"],
["/docs/nodes/memory-add-node","/docs/nodes/data/memory-add-node"],
["/docs/nodes/memory-retrieve-node","/docs/nodes/data/memory-retrieve-node"],
["/docs/nodes/code-node","/docs/nodes/logic/code-node"],
["/docs/nodes/condition-node","/docs/nodes/logic/condition-node"],
["/docs/nodes/variables-node","/docs/nodes/logic/variable-node"],
["/docs/nodes/extract-from-file-node","/docs/nodes/data/extract-from-file-node"],
["/docs/nodes/ai/multimodel-node","/docs/nodes/ai/multimodal-node"],
["/incident/557243","/incident"],
["/incident/542975","/incident"],
["/docs/workflows/deploy","/docs/deployments"],
["/incident/544942","/incident"],
["/docs/workflows/nodes/Logic/condition","/docs/nodes/logic/condition-node"],
// ["/docs/Models","/docs/models"],
["/templates/agentkits/embed/agent-kit-sheets","/agentkits"],
["/docs/bug-bounty-program","/docs/vulnerability-disclosure"],
["/docs/tests/flow-tests","/docs/tests/flow-testing"],
["/incident/541415","/incident"],
["/docs/integrations/apps","/integrations/apps-data-sources"],
["/integrations/aws-s3","/integrations/apps-data-sources/aws-s3"],
["/docs/nodes/extact-from-file-node","/docs/nodes/data/extract-from-file-node"],
["/docs/models/ibm-watsonx-ai","/integrations/models/ibm-watsonx-ai"],
["/docs/nodes/loop-node","/docs/nodes/logic/loop-node"],
["/templates/agentkits/agentic/agent-kit-reasoning.vercel.app","/agentkits"],
["/docs/models/providers/amazon","/integrations/models/bedrock"],
["/docs/tests/flow-tests","/docs/tests/flow-testing"],
["/docs/Trash/logs/Traces","/docs/logs#node-level-traces"],
["/docs/flows/Concepts/branching","/docs/flows/editor"],
// ["/docs/models/Defaults","/docs/models"],
["/workflow","/docs/flows/editor"],
["/docs/Trash/jobs/Connections","/docs/jobs"],
["/docs/flows/Nodes/AI/decision-branch","/docs/nodes/ai/supervisor-node"],
["/docs/models/providers/azure/azure-ai-foundry","/integrations/models/azure-ai-foundry"],
["/docs/support","/docs/slack"],
["/integrations/postgres","/integrations/apps-data-sources/postgres"],
["/docs/nodes/wait-node","/docs/nodes/logic/wait-node"],
["/incident/521378","/incident"],
["/docs/models/cloudflare","/integrations/models/cloudflare"],
["/docs/models/providers/azure","/integrations/models/azure-openai"],
["/docs/tools","/docs/mcp-tools/tools"],
["/docs/tests/flow_tests","/docs/tests/flow-testing"],
["/docs/models/cohere","/integrations/models/cohere"],
["/docs/flows/Nodes/Flow/webhook","/docs/interface/webhooks"],
["/docs/Trash/deploy","/docs/deployments"],
["/docs/flows/Nodes/Flow/api","/docs/nodes/data/api-node"],
["/docs/tests","/docs/tests/flow-testing"],
["/docs/flows/Nodes/AI/RAG","/docs/nodes/ai/rag-node"],
["/docs/tests/Test-Suites","/docs/tests/flow-testing"],
["/docs/models/xai","/integrations/models/xai"],
["/docs/IDE/Prompt IDE","/docs/ide/prompt-ide"],
["/docs/nodes/vector-search-node","/docs/nodes/data/vector-search-node"],
["/docs/integrations/Credentials","/integrations/adding-integration"],
["/docs/mcp/tools","/docs/mcp-tools/mcp"],
["/docs/nodes/crawler-node","/integrations/apps-data-sources/firecrawl"],
["/docs/nodes/execute-flow","/docs/nodes/logic/execute-flow"],
["/integrations/onedrive","/integrations/apps-data-sources/onedrive"],
["/docs/nodes/branch-node","/docs/nodes/logic/branch-node"],
["/docs/nodes/loop-node","/docs/nodes/logic/loop-node"],
["/docs/nodes/memory-retrieve-node","/docs/nodes/data/memory-retrieve-node"],
["/docs/integrations/firecrawl","/integrations/apps-data-sources/firecrawl"],
["/docs/test","/docs/tests/flow-testing"],
["/docs/Trash/logs/Retry","/docs/node-logic"],
["/webhook/abc123","/docs/sdk"],
// ["/incident/559061","/incident"],
// ["/incident/550212","/incident"],
// ["/incident/535623","/incident"],
// ["/incident/575396","/incident"],
// ["/incident/530636","/incident"],
// ["/incident/583174","/incident"],
// ["/incident/526253","/incident"],
["/docs/nodes/RAG-node","/docs/nodes/ai/rag-node"],
["/docs/nodes/extact-from-file-node","/docs/nodes/data/extract-from-file-node"],
["/docs/flows/Low-code_Config","/docs/flows/editor"],
["/docs/node/execute-flow","/docs/nodes/logic/execute-flow"],
["/docs/integrations/apps/firecrawl","/integrations/apps-data-sources/firecrawl"],
["/docs/models/together-ai","/integrations/models/together-ai"],
["/v1/changelog","/changelog"],
["/docs/Trash/Settings/API","/docs/sdk"],
["/docs/interface/Webhooks","/docs/interface/webhooks"],
["/docs/studio/role-based-functionalities","/docs/studio-role-based-access"],
["/docs/models/deepinfra","/integrations/models/deepinfra"],
["/docs/nodes/agents/instructor","/docs/agents/supervisor-agent"],
["/docs/bug-bounty-program","/docs/vulnerability-disclosure"],
["/docs/bug-bounty-program","/docs/vulnerability-disclosure"],
["/docs/bug-bounty-program","/docs/vulnerability-disclosure"],
["/guides/tutorials/document-chatbot","/templates/document-chatbot-widget"],
["/docs/studio/Project","/docs/studio-project"],
["/docs/models/model-parameters","/docs/models/model-config"],
["/docs/nodes/agents","/docs/agents"],
["/docs/flows/Nodes/AI/instructor","/docs/agents/supervisor-agent"],
["/docs/studio/Workspace/Roles","/docs/studio-role-based-access"],
["/docs/studio/Project/Settings/Developer Integrations","/integrations/"],
["/docs/flows/Nodes/Apps","/integrations/apps-data-sources"],
["/docs/workflows/Visual Builder","/docs/flows/editor"],
["/docs/workflows/Nodes/Data/chunking","/docs/concepts/rag"],
["/docs/workflows/nodes/Helper/chunking","/docs/concepts/rag"],
["/docs/Trash/graphQL/Setup","/docs/interface/graphql#setting-up"],
["/docs/sdk","/docs/api-integration/sdk"],
["/docs/api","/docs/api-integration/api-key"],
["/docs/nodes/data/vector-search-node","/docs/nodes/data/vectordb-node"],
["/docs/interfaces","/docs/interface"],
["/docs/langfuse","/docs"],
["/docs/studio/variables-and-secrets","/docs/studio-variables-and-secrets"],
["/api","/docs/api-integration/sdk"],
["/docs/ide/code_ide","/docs/ide/code-ide"],
["/docs/deployments/version-control","/docs/version-control"],
["/docs/keys","/docs/studio-keys"],
["/docs/studio","/docs/studio-overview"],
["/startup","/solutions/startup"],
["/templates/agentkits/agentic/agnet-kit-reasoning","/agentkits"],
["/templates/agentkits/assistant/agent-kit-halloween-costume-generator","/templates/agentkits/misc/agent-kit-halloween-costume-generator"],
["/docs/architecture","/docs/ai-middleware/architecture"],
["/careers/culture","/docs/career"],
["/docs/organization/overview","/docs/studio-overview"],
["/docs/flows/flow_config","/docs/flows/flow-config"],
["/startups","/solutions/startup"],
["/docs/flows/Concepts/prompts","/docs/concepts/llm-prompting"],
["/docs/workflows/Concepts/prompts","/docs/concepts/llm-prompting"],
["/docs/workflows/prompts","/docs/concepts/llm-prompting"],
["/careers/jobs","/docs/career"],
["/docs/IDE/1._Prompt_IDE","/docs/ide/prompt-ide"],
["/docs/studio/Workspace","/docs/studio-overview"],
["/start","/"],
["/docs/ide/prompt_ide","/docs/ide/prompt-ide"],
["/agentkits/lib/jobs-data.ts","/agentkits"],
["/docs/mcp-tools","/docs/mcp-tools/tools"],
["/docs/workflows/Low","/docs/flows"],
["/docs/experiments/Test","/docs/tests/flow-testing"],
["/docs/Models/Defaults","/docs/models/benchmark"],
["/docs/playground/Prompt","/docs/ide/prompt-ide"],
["/docs/playground/Code","/docs/ide/code-ide"],
["/docs/Models","/docs/models/benchmark"],
["/docs/integrations/Postgres_SQL","/integrations/apps-data-sources/postgres"],
["/cdn-cgi/l/email-protection","/security"],
["/contact","/request-demo"],
["/docs/flows/Concepts/messages","/docs/concepts/vibe-coding-setup"],
["/docs/Trash/overview","/docs"],
["/docs/nodes/index-node","/docs/nodes/data/vectordb-node"],
["/docs/nodes/scraper-node","/integrations/apps-data-sources/firecrawl"],
["/docs/flows/Nodes/AI/generate-image","/docs/nodes/ai/generate-image-node"],
["/docs/nodes/multimodel-text-node","/docs/nodes/ai/generate-text-node"],
["/docs/models/providers/azure/azure-openai","/integrations/models/azure-openai"],
["/docs/studio/Profile-Settings","/docs"],
["/guides/tutorials/rag-chatbot","/guides"],
["/docs/workflows/Concepts/messages","/docs/concepts/vibe-coding-setup"],
["/docs/nodes/variable-node","/docs/nodes/logic/variable-node"],
["/docs/mcp/mcp","/docs/mcp-tools/mcp"],
["/comparison/langchain","/compare/langchain"],
["/docs/IDE/Prompt","/docs/ide/prompt-ide"],
["/integrations/sharepoint","/integrations/apps-data-sources/sharepoint"],
["/docs/models/providers/azure/azure-ai-hub","/integrations/models/azure-ai-foundry"],
["/Co-Founder","/about-us"],
["/templates/agentkits/embed/agent-kit-embedded-chat","/agentkits"],
["/comparison/langflow","/compare/langflow"],
["/comparison/n8n","/compare/n8n"]


];
// Caution : Overriding /public messes with the assets
const rewrites = [
  // ["/marketplace", "https://marketplace.lamatic.ai/marketplace"],
  // ["/marketplace/sitemap.xml", "https://marketplace.lamatic.ai/sitemap.xml"],
  // ["/marketplace/:path*", "https://marketplace.lamatic.ai/marketplace/:path*"],
  // ["/labs/:path*", "https://labs.lamatic.ai/:path*/"],
  // ["/blog/", "https://blog.lamatic.ai/"],
  ["/compare/:path*/", "https://blog.lamatic.ai/compare/:path*/"],
  ["/blog/:path*/", "https://blog.lamatic.ai/:path*/"],
  ["/blog/:path*", "https://blog.lamatic.ai/:path*"],
  //["/public/:path*", "https://blog.lamatic.ai/public/:path*"],
  ["/content/:path*", "https://blog.lamatic.ai/content/:path*"],
  ["/assets/:path*", "https://blog.lamatic.ai/assets/:path*"],
  ["/sitemap-doc.xml", "/public/sitemap.xml"],
  ["/sitemap-0.xml", "/public/sitemap-0.xml"],
  ["/sitemap.xml", "/public/website-sitemap.xml"],
  ["/.well-known", "/public/.well-known"],
  ["/robots.txt", "/public/robots.txt"],
    [
      "/:path((?!docs|blog|guides|integrations|agentkits|templates|_next|public|assets|images|api|robots.txt|sitemap-0.xml|ambassadors).*)",
      "https://get.lamatic.ai/:path*",
    ],
];
export default withBundleAnalyzer(nextraConfig);