name: Send File Changes

on:
  push:
    branches:
      - github-index-lamatic  # Adjust to your branch as necessary
    paths: 
      - '**.mdx'  # Set File Types here

jobs:
  send-changes:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 2 

    - name: Set File Type Variable
      run: echo "FILE_TYPE=mdx" >> $GITHUB_ENV # Set File Types to Index

    - name: Send File Changes to Webhook
      run: bash .github/scripts/send_changes.sh
      env:
        GITHUB_REF: ${{ github.ref }}
        WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
        WEBHOOK_KEY: ${{ secrets.WEBHOOK_KEY }}
        FILE_TYPE: ${{ env.FILE_TYPE }}
