name: Sync AgentKit Templates

on:
  schedule:
    - cron: '0 0 * * *'

  push:
    branches:
      - main
    paths:
      - 'files/templates/**'

  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run sync script
        run: python .github/scripts/sync_agentkits.py
        env:
          LAMATIC_API_KEY: ${{ secrets.LAMATIC_API_KEY }}