name: Sync AgentKit Templates

on:
  schedule:
    - cron: '0 0 * * *'

  push:
    branches:
      - main
    paths:
      - 'files/templates/**'
      - 'requirements.txt'

  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: 'requirements.txt'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # === FIX 2: Install from requirements.txt ===
          pip install -r requirements.txt

      - name: Run sync script
        run: python scripts/sync-agentkits.py
        env:
          LAMATIC_API_KEY: ${{ secrets.LAMATIC_API_KEY }}